### PR TITLE
My branch2

### PR DESCRIPTION
**Pull request by goujilinouhaila-coder**

### CODE REVIEW

**Comment by pbastide** [comment]
Thank you for your contributions !

However, it looks like there might be some redundancies in this PR, as there are two files named `Suite._exo2.rmd` (one in root directory, and one in `slides` ?

Also, it looks like some of these files are also added in your PR #13. Could you clarify which PR is the most current one, and which I should consider ?

You currently have three PRs going on (#10, #13 and #14). Could you maybe re-organize them, for instance with one PR for new cheat-sheets, and one PR for typos ? That would help me keep better track of the changes you propose.

Finally, could you maybe move the files in adequate repositories ? For instance, `Chap1.rmd ` should not be in folder `usual_distributions`, maybe it would be best to create a new folder, e.g. `chap1` or `CM` in the `cheatsheet` folder ? Same for `Suite_exo2.rmd`, maybe it's place is not under the `slides` repository, but under `TD` ?

Thank you again for making the effort to contribute, and do not hesitate to ask if you have questions !

**Comment by goujilinouhaila-coder** [comment]
I've already delete Chap1.rmd in the folder usual_distributions; and for Suite_exo2.rmd  i moved it under TD repository. I hope it will work this time.

**Comment by pbastide** [comment]
Thank you for taking my comments into account.

However, it seems that you copied the files, but did not delete them. On the PR page on GitHub, if you go to the `Files changed` tab, you'll see that the PR is adding 4 files, including what seems to be three times `Suite_exo2.rmd` at three different locations. You might need to remove some of those from the git repository.

To delete a file in a git repository, you can for instance use `git rm`, see e.g. the answer to this [question](https://stackoverflow.com/questions/2047465/how-can-i-delete-a-file-from-a-git-repository/2047477).

**Comment by pbastide** [comment]
Thank you for cleaning up the PR, it looks much better now !

Since it deals with the TD, I'll maybe let @bcharlier take it from here.

Thanks !

**Pull request closed without merging**
